# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Akretion
org_slug: akretion
rebel_module_groups: []
repo_description: Odoo modules for managing assets, SSO integration
repo_name: Odoo modules for ak hosting
repo_slug: ak-cloud-france-oi
repo_website: https://github.com/akretion/ak-cloud-france-oi
use_pyproject_toml: true
use_ruff: false

